### ISSUE TITLE
analog pin doesn't work

### ISSUE THREAD

**Issue by mkmaxchc** [ArduinoGetStarted/button#13]
Hi, why analog pin (es. A6 or A7) in arduino nano v3 doesn't work with ezbutton library?

**Comment by ArduinoGetStarted** [comment]
Dear @mkmaxchc, 
As mentioned on [digitaRead() ](https://arduinogetstarted.com/reference/digitalread) function: The exception is the Arduino Nano, Pro Mini, and Mini's A6 and A7 pins, which can only be used as analog inputs

**Comment by mkmaxchc** [comment]
thank you very much and sorry for the inconvenience
