### ISSUE TITLE
ezbutton library does not appear in Examples of Arduino IDE 2.0.1

### ISSUE THREAD

**Issue by Jeff-Haas** [ArduinoGetStarted/button#15]
I installed the ezButton library in the new Arduino IDE, version 2.0.1.  The examples do not appear in the File > Examples menu.  

They do appear in the old IDE, 1.8.13

**Comment by ArduinoGetStarted** [comment]
Hello @Jeff-Haas 

This issue belongs to Arduino IDE 2.0.1, not ezButton library
