### ISSUE TITLE
Pullup

### ISSUE THREAD

**Issue by yentzee** [ArduinoGetStarted/button#17]
Hi,
sorry my programming skills are close to zero. I was wondering what would be the right way to setup the internal pullup resistors when using the library. 
thanks for helping

**Comment by ArduinoGetStarted** [comment]
We just released new version 1.0.5 that supports internal pull-up/pull-down, external pull-up/pull-down.

Note:
* Some Arduino boards do not support `INTERNAL_PULLDOWN`
* ESP32 board: Pins GPIO34, GPIO35, GPIO36(VP) and GPIO39(VN) does not support `INTERNAL_PULLDOWN` and `INTERNAL_PULLUP`.
* It is good to read boards manual to check if a pin support `INTERNAL_PULLDOWN` and `INTERNAL_PULLUP`.
