### ISSUE TITLE
Assigning a key from a matrix to a button?

### ISSUE THREAD

**Issue by Kavster89** [ArduinoGetStarted/button#2]
How would I assign a button within a key matrix to an ezButton?

For example I tried this, but doesn't seem to work:

```
ezButton Switch_Up(buttbx.key[9].kchar);
ezButton Switch_Dn(buttbx.key[10].kchar);
```

Thank you in advance!

**Comment by ArduinoGetStarted** [comment]
Hello,
You can use an array. For more detail, please see this post: [https://forum.arduino.cc/index.php?topic=657367.0](https://forum.arduino.cc/index.php?topic=657367.0)
